#!/usr/bin/env python3

import sys
from argparse import ArgumentParser
from controller_parsers import start_parser

def main():

    arg_parser = ArgumentParser()
    arg_parser.add_argument("-v","--verbose",action="store_true",default=False,dest="verbose")

    args = arg_parser.parse_args()

    while True:

        line = sys.stdin.readline()
        if not line:
            break

        parsers = []
        parsers.append(start_parser(line))

        for parser in parsers:
            if not parser.data() is None:
                sys.stdout.write("[%s] %s\n" % (parser.description(),parser.data()))

if __name__ == "__main__":
    main()
